name: Deploy to Amazon EC2

on:
  push:
    branches: [ "development" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'

      - name: Install dependencies
        run: npm install

      - name: Create .env file and set environment variables and building app
        run: |
          echo "Creating .env file"
          echo "NODE_ENV=production" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "IS_PUBLIC_KEY=${{ secrets.IS_PUBLIC_KEY }}" >> .env
          echo ".env file created"
          echo "Building app"
          npm run build
          echo "Building app completed"

      - name: Run stop script
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo "Connected to server"
            cd ~/deploy
            echo "Running stop script"
            ./stop.sh

      - name: Remove existing dist folder on server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo "Connected to server"
            rm -rf ~/Apps/server/dist
            mkdir ~/Apps/server/dist
            echo "Removed existing dist folder"
      

      - name: Upload dist folder
        run: |
          echo "Creating SSH key file"
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key
          echo "Uploading dist folder"
          scp -r -i ssh_key -o StrictHostKeyChecking=no dist/* ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }}:~/Apps/server/dist/
          echo "Uploaded dist folder"
          echo "Uploading bun.lockb"
          scp -r -i ssh_key -o StrictHostKeyChecking=no bun.lockb ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }}:~/Apps/server/
          echo "Uploaded bun.lockb"
          echo "Uploading env file"
          scp -r -i ssh_key -o StrictHostKeyChecking=no .env ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST }}:~/Apps/server/
          echo "Uploaded .env"
          rm ssh_key

      - name: Run server script
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            echo "Connected to server"
            cd ~/deploy
            echo "Running start script"
            ./start-server.sh
